---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 4855122952-jLxgEMhWJJIL4xS2nJgNY1SIhhbEqARdeVPCSHt
:access_token_secret: 1JZZTinkIf4foj1e7Kl9cAJ2XtR6K5frZQa93fQPmEgTv
